### ISSUE TITLE
Suggested edit

### ISSUE THREAD

**Issue by barenbido** [Dewalt-arch/pimpmy-phprevshell#1]
Hi,
If you were to do the following, you'd add an optional 2nd argument for the interface:
```
# To use for a different nic interface supply a second arg
if [ "$2" = "" ]
  then
    interface="tun0"
  else
    interface="$2"
    echo -e "You supplied "$2" as your desired interface and you chose port "$1" Make sure the IP matches your intentions at the end."
fi
```
I hope you like it. I did this, saved it as phprevshell and added it to my path. 
So now using whatever file structure for notes on a ctf or any engagement I can
```
$phprevshell port [interface]
```
And get a custom revshell right there!
I love your idea, thanks.

**Comment by Dewalt-arch** [comment]
Thank you for the suggestion!

This script does not get 'much' attention, although there is no reason why something like this could 
not be added/implemented to make it a bit more functional, look for an update to the script sometime 
this coming weekend.

Thank you
